#####################################################################
#
# 项目配置
#
#####################################################################
server:
  port: 80
#####################################################################
#
# 配置文件选择
#
#####################################################################
spring:
  cache:
    type: redis
    redis:
      key-prefix: wechat_control_
      time-to-live: 60000
  profiles:
    active: @env@
  application:
    name: 微信中控服务
